name: 'linter'
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    if: "{contains(github.event.head_commit.message, 'skip ci') == false}"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Install dependencies'
        run: pnpm install

      - name: 'Check Prettier standards'
        run: pnpm check-format
