#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing, and building your staging files before committing'

# Run linting using pnpm lint
pnpm lint || (
    echo '🚫❌🚫❌ Linting failed. Please fix the linting errors and try committing again. 🚫❌🚫❌';
    false;
)

# Run Prettier on staged files using pretty-quick
npx pretty-quick --staged || (
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes, and try committing again.';
    false;
)

echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'