#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo '🏗️👷 Styling, testing and building your stagging files before committing'
npx pretty-quick --staged || (
    echo '🤢🤮🤢🤮 Its F**KING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run npm run format, add changes and try commit again.';
    false;
)
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
